### PR TITLE
Nominate Michael and Jann as sig-leads for sig-security

### PR DESCRIPTION
**Pull request by todaywasawesome**
Michael has been defacto sig-lead for a while. He's organized better reporting systems, takes the lead on the administration of the project, and he has several times made proactive changes to improve project security and orientation. He is the natural choice for the job.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
+1

**Comment by todaywasawesome** [comment]
Tagged all sig-security members for review. Sig-security doesn't have a formal nomination and voting process so I think it's best we shoot for 7 👍 (majority)

**Review by hblixt — APPROVED** [review]
+1

**Comment by 34fathombelow** [comment]
+1

**Comment by hblixt** [comment]
Actually, SIG leads are approved by the maintainers, not the SIG itself, so the next voting opportunity would be in the Jan maintainers meeting, since I dont think it's critical enough to start a full maintainer github vote.

**Comment by edlee2121** [comment]
+1
Would also like to nominate @jannfis as co-lead.

**Comment by zachaller** [comment]
+1

**Comment by wtam2018** [comment]
+1

**Comment by jannfis** [comment]
+1

**Review by jmeridth — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
+1

**Review by crenshaw-dev — APPROVED** [review]

**Review by zachaller — APPROVED** [review]

**Pull request merged**
