### PR TITLE
Update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by edlee2121**

### CODE REVIEW

**Review by hblixt — APPROVED** [review]
LGTM

**Review by alexmt — APPROVED** [review]
LGTM

**Review by dtaniwaki — APPROVED** [review]
LGTM! Should I close #71, which should be exactly the same change?

**Comment by edlee2121** [comment]
Daisuke, they are two different documents.

**Comment by dtaniwaki** [comment]
Could you also check the following PRs as I belong to Ubie now?
https://github.com/argoproj/argo-site/pull/66
https://github.com/argoproj/argo-site/pull/67

**Pull request merged**
