### PR TITLE
docs: Add 3rd party SLSA Assessment

### PR DESCRIPTION
**Pull request by found-it**
Publishing the SLSA Assessment commissioned by the CNCF.

CC @crenshaw-dev

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
Excellent!

**Comment by todaywasawesome** [comment]
@found-it you might want to verify your commit. I would also add a link to the SLSA assessment to the news section of the readme.

**Comment by found-it** [comment]
Hey @todaywasawesome thanks for the advice! I added it to the news section, let me know if you need anything else or have any nitpicks. On the Unverified commit, I use [sigstore's gitsign](https://github.com/sigstore/gitsign) to sign my commits and sadly GitHub doesn't show them as verified yet ([more info here](https://github.com/sigstore/gitsign#why-doesnt-github-show-commits-as-verified)). They can be verified using gitsign itself

```sh
$ gitsign verify --certificate-identity=james.petersen@chainguard.dev --certificate-oidc-issuer=https://accounts.google.com slsa-assessment-2023
tlog index: 18297822
gitsign: Signature made using certificate ID 0xa4097548f4d4b4106df32dd0f04d2e71601f3e33 | CN=sigstore-intermediate,O=sigstore.dev
gitsign: Good signature from [james.petersen@chainguard.dev](https://accounts.google.com)
Validated Git signature: true
Validated Rekor entry: true
Validated Certificate claims: true
```

Or once the PR is merged
```sh
$ gitsign verify --certificate-identity=james.petersen@chainguard.dev --certificate-oidc-issuer=https://accounts.google.com HEAD
```

**Review by 34fathombelow — APPROVED** [review]
Brilliant work! lgtm

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
