### PR TITLE
Add Caelan Urquhart to sig-marketing

### PR DESCRIPTION
**Pull request by todaywasawesome**
Caelan has been a huge booster and link in the Argo Workflows community and has helped review talks and organize two ArgoCon's. I think his help has been invaluable and I propose he be added to sig-marketing.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@todaywasawesome is there any process that needs to be followed here besides someone approving the PR and merging? Obviously wanna let the SIG drive these changes, but if you represent the SIG then I think the work is done.

**Comment by hblixt** [comment]
> @todaywasawesome is there any process that needs to be followed here besides someone approving the PR and merging? Obviously wanna let the SIG drive these changes, but if you represent the SIG then I think the work is done.

AFAIK, it's only SIG named/specific roles, e.g. secretary that need maintainer approval, so to just add members, I agree with @crenshaw-dev, there's really nothing more needed.

**Review by hblixt — APPROVED** [review]
LGTM

**Comment by christianh814** [comment]
+1 for me!

**Comment by todaywasawesome** [comment]
The docs just say maintainer's need to nominate and approve so yeah I think we're good.

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
