### PR TITLE
Update argo.svg to repair imperfections

### PR DESCRIPTION
**Pull request by falcone-design**
Updated argo.svg that fixes the oddities, inconsistencies, and small imperfections with the first iteration of the Argo logo. If you zoom in closely on the original .svg, you can see some of these geometric imperfections. These become more obvious when the Argo logo (Argonaut) is printed/blown up to a large size, either on large displays or on large printed assets used for conferences and the like. 

This rebuild is courtesy of the Pipekit team. We hope the entire Argo community can benefit from a more polished and scale-friendly Argonaut.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
ha, nice try!

image

But seriously, thank you! Should we try to get the updates [upstream](https://github.com/cncf/artwork/blob/main/examples/graduated.md#argo-logos) as well?

**Comment by crenshaw-dev** [comment]
I see some subtle variations besides geometry fixes (no shadow of the helmet overlaying the body, reflection on the left side is a bit smaller). Are we shooting for significant changes, or should we keep it closer to the original?

**Comment by wanghong230** [comment]
We have the orginal Argo logo designer with us, so I wish to have his input.

**Comment by hblixt** [comment]
The source of truth for all CNCF logo(s) is https://github.com/cncf/artwork/tree/main/projects/argo and technically CNCF owns the Argo logo and it's trademarked, so we'd at the very least have to check in with them. 
If the same imperfections are there in the CNCF version (doesnt look like it from a first glance) and they are ok with the additional changes, we should work with them to have it replaced in their repos, which is what I think Michael eluded to. 
I would argue we shouldnt even host our own version (I didnt even know we did)

**Comment by rahul-d-hide** [comment]
Thanks for sharing. I reviewed the revised version and observed the following changes:
- Changed the facial expressions/smile- teeth and mouth shape
- Changed leg thickness
- Changed helmet highlight
- Added Pipekit name in the eye
- Removed helmet shadow

These changes may not help us improve the printing quality or address the scaling issues. 

Firstly, I suggest not using the repository image for printing or other purposes. Instead, please look for other threads where we have shared high-resolution image assets. [](https://github.com/kubeflow/website/issues/99)

We are currently working on creating more comprehensive logo usage guidelines, updating our asset library with different file formats, and developing a 3D version and an Argo icon for use in product and architectural diagrams to ensure consistency. We will provide more details on this soon.

**Comment by edlee2121** [comment]
For this iteration, would like to stay with the original image and feel as much as possible and only fix the graphical imperfections.

**Comment by JPZ13** [comment]
Hi all - we ensured there is no Pipekit text by the eye and are potentially open to even donating the raw Figma/Photoshop files so that the logo can be more of a community thing. Unfortunately, that's all the capacity we have in the short term. We don't have enough bandwidth at the moment to get buy-in from different stakeholders and put in further design cycles on this.

Are y'all interested in this high-fidelity logo? If so, feel free to use it. If not, I'll close the PR

**Comment by edlee2121** [comment]
Thanks for all the work you and team put in @JPZ13!
I think that anything other than just fixing the imperfections is going to require a lot more stakeholder feedback, including CNCF, who owns the logo. So we should probably close the PR for now.
Thanks again for taking an interest in improving the logo!

**Comment by JPZ13** [comment]
Thanks @edlee2121! Closing

**Comment by edlee2121** [comment]
FYI, SIG marketing will discuss whether to remove all logo assents from our github and just refer them to the assets maintained by the CNCF.

**Pull request closed without merging**
