### PR TITLE
Argoproj promotions/membership

### PR DESCRIPTION
**Pull request by crenshaw-dev**
# Argoproj promotions/membership

Every quarter, the Argoproj maintainers review requests for project membership and promotions (read about the roles [here](https://github.com/argoproj/argoproj/blob/master/community/membership.md#community-membership)). The changes below recognize the incredible efforts ([graphed on CNCF devstats](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=All&var-users=%22juliev0%22&var-users=%22zachaller%22&var-users=%22terrytangyuan%22&var-users=%22wilsonwu%22&var-users=%22Joibel%22&var-users=%22dfarr%22&var-users=%22isubasinghe%22&var-users=%22blakepettersson%22&var-users=%22gdsoumya%22&from=now-6M&to=now)) and commitment to the project by these people. Thank you so much!

## 🚀  Maintainer promotions

Congrats to the following contributors for their promotions:

* Zach Aller (@zachaller) to Lead of Argo Rollouts
* Yuan Tang (@terrytangyuan) to Lead of Argo Workflows
* Julie Vogelman (@juliev0) to Approver in Argo Workflows
* Soumya Ghosh Dastidar (@gdsoumya) to Reviewer in Argo CD
* Blake Pettersson (@blakepettersson) to Reviewer in Argo CD
* Isitha Subasinghe (@isubasinghe) to Reviewer in Argo Workflows

## ⭐  New members

An additional congratulations to the following folks for becoming Argoproj members:

* Alan Clucas (@Joibel)
* David Farr (@dfarr)
* Robert Kotcher (@robertkotcher)
* Raymond Wong (@rwong2888)
* Wilson Wu (@wilsonwu)

You all will receive invitations on GitHub to become members of the Argoproj organization.

## 🎓 Alumni

The maintainers document contains a new section for folks who were previously maintainers but have been inactive for at least a year. While not currently active, they deserve continued recognition for their impact on the project!

I'd like to personally thank Simon Behar, who was one of the first Argoproj maintainers I interacted with around 3 years ago. Without their work on the project, my journey with Argoproj likely would have looked much different. Thanks for everything, Simon!

Closes https://github.com/argoproj/argoproj/issues/158
Closes https://github.com/argoproj/argoproj/issues/181
Closes https://github.com/argoproj/argoproj/issues/187
Closes https://github.com/argoproj/argoproj/issues/195
Closes https://github.com/argoproj/argoproj/issues/198
Closes https://github.com/argoproj/argoproj/issues/200
Closes https://github.com/argoproj/argoproj/issues/201
Closes https://github.com/argoproj/argoproj/issues/204
Closes https://github.com/argoproj/argoproj/issues/205
Closes https://github.com/argoproj/argoproj/issues/206
Closes https://github.com/argoproj/argoproj/issues/207

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Tasks for maintainers:
- [x] Add new approvers to #argo-approvers
- [x] Add new maintainers to #argo-maintainers
- [ ] @zachaller please open a PR to update the [Rollouts OWNERS file](https://github.com/argoproj/argo-rollouts/blob/master/OWNERS).
- [ ] @jessesuen or @alexmt please add Zach as an admin on the Rollouts repo.
- [ ] @terrytangyuan please open a PR to update the [Workflows OWNERS file](https://github.com/argoproj/argo-workflows/blob/master/OWNERS).
- [ ] @sarabala1979 or @alexec please add Terry as an Admin on the Workflows repo.
- [ ] @juliev0 please open a PR to update the [Workflows OWNERS file](https://github.com/argoproj/argo-workflows/blob/master/OWNERS).
- [ ] @sarabala1979 or @alexec please add Julie to the [Argo-workflow-approvers team](https://github.com/orgs/argoproj/teams/argo-workflow-approvers).
- [ ] @alexec would you mind sending Argoproj invitations to the new members?

**Review by alexmt — APPROVED** [review]

**Comment by alexec** [comment]
@crenshaw-dev can you book something onto my calendar?

**Review by jessesuen — APPROVED** [review]

**Review by sarabala1979 — APPROVED** [review]

**Comment by terrytangyuan** [comment]
This file needs to be updated as well: https://github.com/argoproj/argoproj/blob/master/OWNERS

**Comment by alexec** [comment]
image

**Comment by crenshaw-dev** [comment]
Thanks, all! Feel free to tag me here if I've missed anything.

**Pull request merged**
