### PR TITLE
governance change: prune membership after 6 months

### PR DESCRIPTION
**Pull request by crenshaw-dev**
This is mostly because I can't find a devstats graph that shows activity for an individual >6mo back. This is the best I've found: https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=All&var-users=%22crenshaw-dev%22&from=now-1y&to=now

But also I think 6 months is reasonable. It's easy to add people back if we need to.

Since I'm submitting this on Monday, Oct. 31, voting will close on Monday, November 14.

Rules for governance changes: https://github.com/argoproj/argoproj/blob/master/community/GOVERNANCE.md#changes-to-governance

### CODE REVIEW

**Comment by edlee2121** [comment]
@crenshaw-dev Since folks can be on extended vacation or have important projects come up at work. I'd prefer to keep it at 12 months. Can we use the GitHub activity history instead of devstat?

**Comment by crenshaw-dev** [comment]
@edlee2121 does GitHub activity history provide a way to look at history specific to Argoproj repos?

**Comment by crenshaw-dev** [comment]
Since devstats counts _any_ contribution (including simply commenting on an issue) and reinstating a removed member is very easy, I'm still in favor of 6mo. (Someone could literally just comment on this issue if they wanted to avoid being removed).

But if we can find a good way to look at 12mo stats, that solves my main concern.

**Comment by zachaller** [comment]
There is a comment on inactive page that says this `Note: Devstats does not take into account non-code contributions. If a non-code contributing member is accidentally removed this way, they may open an issue to quickly be re-instated.`  I think that is false if we are using devstats "Contributions" metric. Do we want to remove that and also possibly provide the link of that graph that will be used?

**Comment by crenshaw-dev** [comment]
@zachaller updated

**Comment by zachaller** [comment]
+1

**Comment by crenshaw-dev** [comment]
Ah, voting is in thumbs up and down on the PR. According to the Rule Book. 😄

**Comment by hblixt** [comment]
Wouldnt this work? You can't explicitly search for an individual, but even across all repository groups there are just five pages so ctrl-f through the pages is pretty fast. 
https://argo.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All

**Comment by crenshaw-dev** [comment]
@hblixt fair. A bit tedious, but could be done.

**Comment by todaywasawesome** [comment]
I agree with @edlee2121 there are a lot of life changes that can be resolved within 6-12 months. I'd prefer to keep it where it is.

**Comment by crenshaw-dev** [comment]
Closing in favor of keeping 6mo and using the devstats table Henrik found.

**Comment by edlee2121** [comment]
I think you meant 12 months, Michael :-)

**Comment by crenshaw-dev** [comment]
lol yep.

**Pull request closed without merging**
