### PR TITLE
Argoproj promotions/membership

### PR DESCRIPTION
**Pull request by crenshaw-dev**
# Argoproj promotions/membership

Every quarter, the Argoproj maintainers review requests for project membership and promotions (read about the roles [here](https://github.com/argoproj/argoproj/blob/master/community/membership.md#community-membership)). The changes below recognize a truly mind-boggling amount of effort ([graphed on CNCF devstats](https://argo.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=All&var-users=%22alexef%22&var-users=%22schakrad%22&var-users=%22isubasinghe%22&var-users=%2234fathombelow%22&var-users=%22reggie-k%22&var-users=%22blakepettersson%22&var-users=%22juliev0%22&var-users=%22my-git9%22&var-users=%22notfromstatefarm%22&var-users=%22zachaller%22&var-users=%22rohankmr414%22&var-users=%22tico24%22&var-users=%22ashutosh16%22&from=now-6M&to=now)) and commitment to the project by these thirteen people. Thank you so much!

## 🚀  Maintainer promotions

Congrats to Zach Aller (@zachaller), Julie Vogelman (@juliev0), and Justin Marquis (@34fathombelow) on their membership promotions!

## ⭐  New members

An additional congratulations to the following folks for becoming Argoproj members:

* @alexef
* @ashutosh16
* @blakepettersson
* @isubasinghe
* @my-git9
* @notfromstatefarm
* @reggie-k
* @rohankmr414
* @schakrad
* @tico24

You all will receive invitations on GitHub to become members of the Argoproj organization.

## 🎓 Alumni

The maintainers document contains a new section for folks who were previously maintainers but have been inactive for at least a year. While not currently active, they deserve continued recognition for their impact on the project!

Closes https://github.com/argoproj/argoproj/issues/136
Closes https://github.com/argoproj/argoproj/issues/147
Closes https://github.com/argoproj/argoproj/issues/151
Closes https://github.com/argoproj/argoproj/issues/154
Closes https://github.com/argoproj/argoproj/issues/160
Closes https://github.com/argoproj/argoproj/issues/162
Closes https://github.com/argoproj/argoproj/issues/163
Closes https://github.com/argoproj/argoproj/issues/164
Closes https://github.com/argoproj/argoproj/issues/165
Closes https://github.com/argoproj/argoproj/issues/166
Closes https://github.com/argoproj/argoproj/issues/167
Closes https://github.com/argoproj/argoproj/issues/168
Closes https://github.com/argoproj/argoproj/issues/169

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
LGTM. Congrats everyone and welcome to the team!

**Review by alexef — APPROVED** [review]

**Comment by alexec** [comment]
Done.

**Comment by alexec** [comment]
2 already accepted invite, 8 pending:

image

**Comment by crenshaw-dev** [comment]
@alexec can you double check that an invite was sent to @blakepettersson?

**Comment by zachaller** [comment]
@alexec @edlee2121 @crenshaw-dev are we waiting on something to happen before this gets merged?

**Review by edlee2121 — APPROVED** [review]

**Comment by notfromstatefarm** [comment]
Hey guys! It seems I never received the invite. I was AFK for a couple of months dealing with some family health issues but I'm back and ready to roll.

cc @crenshaw-dev

**Pull request merged**
